texto = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(texto)}')
print('Só tem espaços?', texto.isspace())
print('É um numero? ', texto.isnumeric())
print('É alfabetico? ', texto.isalpha())
print('É alfanumerico? ', texto.isalnum())
print('Esta em maiusculo? ', texto.isupper())
print('Esta em minusculo? ', texto.islower())
print('Esta capitalizado? ', texto.istitle())
