n1 = float(input('Coloque os metros:'))
print('o valor em quilometro é:', n1 / 1000,'km')
print('o valor em hectometro é:', n1 /100,'hm')
print('o valor em decametro é:', n1 / 10,'dam')
print('o valor em metros é:', n1,'m')
print('o valor em decimentros é:', n1 * 10, 'dm')
print('o valor em centimetros é:', n1 * 100,'cm')
print('o valor em milimetros é:', n1 * 1000,'mm')
